// name, url
const LYNNS = [
    [ "Boredlynn", "assets/actors/amberlynn_bored.png" ],
    [ "Angrylynn", "assets/actors/amberlynn_pissed.png" ],
    [ "Leaveenlynn", "assets/actors/amberlynn_leaveen.png" ],
    [ "Gasplynn", "assets/actors/amberlynn_gasp.png" ],
    [ "Mookbonglynn", "assets/actors/amberlynn_mook-bong.png" ],
    [ "Pointerlynn", "assets/actors/amberlynn_pointer.png" ],
    [ "Shadowlynn", "assets/actors/amberlynn_shadow.png" ],
    [ "Heyguyslynn", "assets/actors/amberlynn_heyguys.png" ],
    [ "Laserlynn", "assets/actors/amberlynn_laser.png" ],
    [ "Confusedlynn", "assets/actors/amberlynn_confused.png" ],
    [ "Readerlynn", "assets/actors/amberlynn_books.png" ],
    [ "Cacklelynn", "assets/actors/amberlynn_cacklelynn.png" ],
    [ "Frownylynn", "assets/actors/amberlynn_frowny.png" ],
    [ "Backwardslynn", "assets/actors/amberlynn_backwards.png" ],
    [ "Youtubelynn", "assets/actors/amberlynn_laptopyt.png" ],
    [ "Stirlynn", "assets/actors/amberlynn_stir.png" ],
    [ "Cucumberlynn", "assets/actors/amberlynn_cucumber.png" ],
    [ "Mentallynn", "assets/actors/amberlynn_mentalthings.png" ],
    [ "Scaredlynn", "assets/actors/amberlynn_scared.png" ],
    [ "Pizzalynn", "assets/actors/amberlynn_pizza.png" ],
    [ "Potlynn", "assets/actors/amberlynn_bigpot.png" ],
    [ "Siplynn", "assets/actors/amberlynn_sip.png" ],
    [ "Guiltylynn", "assets/actors/amberlynn_guilty.png" ],
    [ "Smuglynn", "assets/actors/amberlynn_smug.png" ],
    [ "Saladlynn", "assets/actors/amberlynn_salad.png" ],
    [ "Ewlynn", "assets/actors/amberlynn_disgusted.png" ],
]

const NUM_LYNNS = LYNNS.length